require 'rake'
require 'rspec/core/rake_task'
require 'json'
require 'chef'

#require 'rubygems'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
    targets = []
    #Dir.glob('./spec/*').each do |dir|
    #    next unless File.directory?(dir)
    #    target = File.basename(dir)
    #    target = "_#{target}" if target == "default"
    #    targets << target
    #end

    Dir.glob('./nodes/*.json').each do | node |
        target = File.basename(node,".json")
        target = "_#{target}" if target == "default"
        targets << target
    end
    
    task :all     => targets
    task :default => :all
    
    targets.each do |target|
        original_target = target == "_default" ? target[1..-1] : target
        desc "Run serverspec tests to #{original_target}"
        RSpec::Core::RakeTask.new(target.to_sym) do |t|
            ENV['TARGET_HOST'] = original_target
            json = open("nodes/#{original_target}.json") do | io |
                JSON.load(io)
            end
            recipes = Chef::RunList.new(*json['run_list']).expand("_default", "disk").recipes
            #t.pattern = ['spec/testcase/{' + recipes.join('_spec.rb,') + '}']
            #recipes = recipes.join('_spec.rb,') + '_spec.rb'
            puts '--------------------------------------------'
            puts 'Apply Serverspec to ' + original_target + '.json'
            puts recipes
            puts '--------------------------------------------'
            t.pattern = ['spec/testcase/{' + recipes.join('_spec.rb,') + '_spec.rb}']
        end
    end
end



